name: Garak pytest - Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore test cache artifacts
        id: cache-artifacts-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .cache/garak/data
            .cache/huggingface
          key: garak-test-resources-shared

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip cache purge

      - name: Test with pytest
        run: |
          python -m pytest tests/
